/** لینک‌های دسته برای منوی ناوبری — هماهنگ با اسلاگ‌های دیتابیس/سید */
export const NAV_CATEGORIES = [
  { href: "/categories/goldan", label: "گلدان" },
  { href: "/categories/tandis", label: "تندیس" },
  { href: "/categories/shamdan", label: "جاشمعی" },
  { href: "/categories/ghab", label: "قاب" },
  { href: "/categories/ghab-fiber", label: "قاب فایبر" },
  { href: "/categories/dastmal-cover", label: "کاور دستمال" },
  { href: "/categories/heyvanat", label: "حیوانات" },
  { href: "/categories/book-holder", label: "هولدر کتاب" },
  { href: "/categories/sini", label: "سینی" },
  { href: "/categories/abajor", label: "اباژور" },
  { href: "/categories/fereshte-mojasame", label: "مجسمه فرشته" },
  { href: "/categories/fereshte-divari", label: "فرشته دیواری" },
  { href: "/categories/shamdan-divari", label: "جاشمعی دیواری" },
  { href: "/categories/konsol", label: "کنسول" },
  { href: "/categories/paye-miz", label: "پایه میز" },
  { href: "/categories/divarkoob", label: "دیوارکوب" },
  { href: "/categories/ghab-payedar", label: "قاب پایه دار" },
  { href: "/categories/banka", label: "بانکه" },
  { href: "/categories/kado", label: "کدو" },
  { href: "/categories/christmas", label: "کریسمسی" },
  { href: "/categories/pazirayi", label: "ظرف پذیرایی" },
  { href: "/categories/haftsin", label: "هفتسین" },
  { href: "/categories/crystal", label: "کریستال" },
] as const;
